import { graphMutate } from "./client";

export interface BoostConfig {
  daily_budget: string; // in cents
  duration_days: number;
  targeting_type: "broad" | "custom";
  countries: string[]; // ISO country codes, e.g. ['VN'] or WORLDWIDE_COUNTRIES
  age_min?: number;
  age_max?: number;
}

// All Meta-supported country codes for worldwide targeting
export const WORLDWIDE_COUNTRIES = [
  "AF",
  "AL",
  "DZ",
  "AD",
  "AO",
  "AG",
  "AR",
  "AM",
  "AU",
  "AT",
  "AZ",
  "BS",
  "BH",
  "BD",
  "BB",
  "BY",
  "BE",
  "BZ",
  "BJ",
  "BT",
  "BO",
  "BA",
  "BW",
  "BR",
  "BN",
  "BG",
  "BF",
  "BI",
  "CV",
  "KH",
  "CM",
  "CA",
  "CF",
  "TD",
  "CL",
  "CN",
  "CO",
  "KM",
  "CG",
  "CD",
  "CR",
  "HR",
  "CU",
  "CY",
  "CZ",
  "DK",
  "DJ",
  "DM",
  "DO",
  "EC",
  "EG",
  "SV",
  "GQ",
  "ER",
  "EE",
  "SZ",
  "ET",
  "FJ",
  "FI",
  "FR",
  "GA",
  "GM",
  "GE",
  "DE",
  "GH",
  "GR",
  "GD",
  "GT",
  "GN",
  "GW",
  "GY",
  "HT",
  "HN",
  "HU",
  "IS",
  "IN",
  "ID",
  "IR",
  "IQ",
  "IE",
  "IL",
  "IT",
  "JM",
  "JP",
  "JO",
  "KZ",
  "KE",
  "KI",
  "KP",
  "KR",
  "KW",
  "KG",
  "LA",
  "LV",
  "LB",
  "LS",
  "LR",
  "LY",
  "LI",
  "LT",
  "LU",
  "MG",
  "MW",
  "MY",
  "MV",
  "ML",
  "MT",
  "MH",
  "MR",
  "MU",
  "MX",
  "FM",
  "MD",
  "MC",
  "MN",
  "ME",
  "MA",
  "MZ",
  "MM",
  "NA",
  "NR",
  "NP",
  "NL",
  "NZ",
  "NI",
  "NE",
  "NG",
  "MK",
  "NO",
  "OM",
  "PK",
  "PW",
  "PA",
  "PG",
  "PY",
  "PE",
  "PH",
  "PL",
  "PT",
  "QA",
  "RO",
  "RU",
  "RW",
  "KN",
  "LC",
  "VC",
  "WS",
  "SM",
  "ST",
  "SA",
  "SN",
  "RS",
  "SC",
  "SL",
  "SG",
  "SK",
  "SI",
  "SB",
  "SO",
  "ZA",
  "SS",
  "ES",
  "LK",
  "SD",
  "SR",
  "SE",
  "CH",
  "SY",
  "TW",
  "TJ",
  "TZ",
  "TH",
  "TL",
  "TG",
  "TO",
  "TT",
  "TN",
  "TR",
  "TM",
  "TV",
  "UG",
  "UA",
  "AE",
  "GB",
  "US",
  "UY",
  "UZ",
  "VU",
  "VE",
  "VN",
  "YE",
  "ZM",
  "ZW",
];

export async function boostPost(
  adAccountId: string,
  pageId: string,
  postId: string,
  config: BoostConfig,
  token: string,
): Promise<{ campaign_id: string }> {
  // Step 1: Create campaign
  const campaign = await graphMutate<{ id: string }>(
    `/act_${adAccountId}/campaigns`,
    {
      name: `Boost Post - ${postId}`,
      objective: "OUTCOME_ENGAGEMENT",
      status: "ACTIVE",
      special_ad_categories: "[]",
      is_adset_budget_sharing_enabled: "false",
    },
    token,
  );

  // Step 2: Create adset
  // connections/friends_of_connections deprecated in API v25 — use geo + age targeting only
  const geoLocations = { countries: config.countries ?? ["VN"] };

  const targeting =
    config.targeting_type === "broad"
      ? JSON.stringify({ geo_locations: geoLocations })
      : JSON.stringify({
          age_min: config.age_min ?? 18,
          age_max: config.age_max ?? 65,
          geo_locations: geoLocations,
        });

  const endTime = new Date();
  // Add duration + 1 extra day to satisfy Meta's minimum 24h schedule requirement
  endTime.setDate(endTime.getDate() + config.duration_days + 1);

  const adset = await graphMutate<{ id: string }>(
    `/act_${adAccountId}/adsets`,
    {
      name: `Boost Adset - ${postId}`,
      campaign_id: campaign.id,
      daily_budget: config.daily_budget,
      billing_event: "IMPRESSIONS",
      optimization_goal: "LINK_CLICKS",
      bid_strategy: "LOWEST_COST_WITHOUT_CAP",
      targeting,
      status: "ACTIVE",
      end_time: endTime.toISOString(),
    },
    token,
  );

  // Step 3: Create ad
  await graphMutate<{ id: string }>(
    `/act_${adAccountId}/ads`,
    {
      name: `Boost Ad - ${postId}`,
      adset_id: adset.id,
      creative: JSON.stringify({
        object_story_id: `${pageId}_${postId.includes("_") ? postId.split("_").pop()! : postId}`,
      }),
      status: "ACTIVE",
    },
    token,
  );

  return { campaign_id: campaign.id };
}
